### PR TITLE
Add share button to share current configuration

### LINKED ISSUE #20: [💡 Feature request] create a copy to clipboard with the current informations on the page
One cool way to use this webapp would be to send it to non techincal users to get a report of their situation (useful for debugging)

The easiest way would be to include a copy to clipboard button that will copy the information in a dev digestable way. The step up could be add the ability to add a query parameter (reportTo) and onload send an email to it with the current information (so that one could just send a link with their email address setupped and immediately get back a feedback.

Obviosuly this second one it's far more expensive and it also has possible security implications to reason of but it could even be a form of profit for you (it could very easily become a paid feature but i don't know if that's where this project is headed).

If you are ok with those i can even start to work on those (to be fair i never used nuxt and i barely used vue but it shuldn't be to difficult and that is what code reviews are for right? RIGHT?)

Joking aside let me know what do you think about the proposal and let me know if you are ok with me working on them.

### PR DESCRIPTION
**Pull request by paoloricciuti**
Fixes #20

- I've added the webApiExportList and the test to check if every api is present in the array
- I've also added the encode and decode functions to encode and decode the current configuration into a number
- I've added the share page that is similar to index but with uses the query param to populate the cards (i've also moved the code to a shared component to facilitate future modification to the template)
- I've added the share button on top of the index page that opens a modal to copy the sharable url

Things i'd like to finish before merging:

- I would like to add a github action to run tests on new pr
- Figure out what to do when we click from the share page on an api card

### CODE REVIEW

**Comment by toniengelhardt** [comment]
Great work, looks quite good already! 

Let me quickly add the automatic testing CI (have a yaml already) and simplify the routing a bit so that we do not need the extra page.

Btw, everything in `/utils` is automatically imported by Nuxt as well as `shallowRef` and  all the components, see [docs](https://nuxt.com/docs/guide/concepts/auto-imports). If you are using VS Code I'd suggest enabling [takeover mode](https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode) with Volar to make the linter recognize that correctly.

**Comment by paoloricciuti** [comment]
> Great work, looks quite good already!
> 
> Let me quickly add the automatic testing CI (have a yaml already) and simplify the routing a bit so that we do not need the extra page.

Interested in how I should do this: an optional route param?

> Btw, everything in `/utils` is automatically imported by Nuxt as well as `shallowRef` and all the components, see [docs](https://nuxt.com/docs/guide/concepts/auto-imports). If you are using VS Code I'd suggest enabling [takeover mode](https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode) with Volar to make the linter recognize that correctly.

I was having some problem with vitest to be fair: trying to run that test failed because it didn't imported shallow ref so I fixed it by hand

**Comment by toniengelhardt** [comment]
Ok, so I made a new PR based off of this one: https://github.com/toniengelhardt/webapicheck/pull/28 

Instead of having a special 'share' URL it just has a 'status' query param now. This simplifies the logic a lot and there are basically no changes needed besides in `useTestWebApis`. It either takes the results from the URL if available, otherwise runs the test. This way we are also not limited to the index page only, in principle any page can now be opened with a specified status. I prefixed it with `v1` just in case at some point we want to break it and keep backward comp.

I also moved stuff around a bit and tweaked the styling.

There is only one thing left to do now: instead of encoding to integer I would encode to `base64url`, which is kind of a standard for these kind of things and a bit more efficient in terms of URL size. Do you want to do it? Otherwise I can give it a shot as well.

Tests, typecheck, and linting are now running automatically when you create a PR to main.

And I disabled the links to the detail page if the status param is set.

Let me know what you think ✌🏽

**Comment by paoloricciuti** [comment]
> Ok, so I made a new PR based off of this one: #28
> 
> Instead of having a special 'share' URL it just has a 'status' query param now. This simplifies the logic a lot and there are basically no changes needed besides in `useTestWebApis`. It either takes the results from the URL if available, otherwise runs the test. This way we are also not limited to the index page only, in principle any page can now be opened with a specified status. I prefixed it with `v1` just in case at some point we want to break it and keep backward comp.
> 
> I also moved stuff around a bit and tweaked the styling.
> 
> There is only one thing left to do now: instead of encoding to integer I would encode to `base64url`, which is kind of a standard for these kind of things and a bit more efficient in terms of URL size. Do you want to do it? Otherwise I can give it a shot as well.
> 
> Tests, typecheck, and linting are now running automatically when you create a PR to main.
> 
> And I disabled the links to the detail page if the status param is set.
> 
> Let me know what you think ✌🏽

Seems very good...I can take care of the base 64 encoding...just to make sure: what do you mean is that instead of transform the binary to base 10 you want it transformed in base 64 right?

**Comment by paoloricciuti** [comment]
@toniengelhardt i've also modified webApiStatusCheck so that if there's a status queryParam it runs the code on the server so we get SSR, if there's not it register the onmounted callback to test the apis on mount.

P.s. also the types are failing because they try to typecheck node_modules, i don't really get why

**Comment by toniengelhardt** [comment]
Ah interesting, I had some errors with SSR, that's why I moved it into the test part, but if it works it's obviously better!

Yes, it should probably ignore typechecking the node_modules, will see if I can exclude it.

**Comment by paoloricciuti** [comment]
Running the preview server has the same effect of the deployed version...i have to investigate this further

**Pull request merged**
